# Generated by Django 4.1.7 on 2023-03-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0003_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
