# Generated by Django 4.1.7 on 2023-03-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_post_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
